### ISSUE TITLE
Pull patches from @rxrbln [2024-10-05]

### ISSUE THREAD

**Issue by lenticularis39** [linux-ia64/linux-ia64#4]
Patches:
- https://svn.exactcode.de/t2/trunk/package/kernel/linux/hotfix-ia64-printk-cont.patch
- https://svn.exactcode.de/t2/trunk/package/kernel/linux/hotfix-ia64-pagesize.patch
- https://svn.exactcode.de/t2/trunk/package/kernel/linux/hotfix-ia64-cpufreq.patch

Add `Signed-off-by: René Rebe <rene@exactcode.de>`.

**Comment by lenticularis39** [comment]
Pulled as f8dfe4b1adaa2bf68771701a672b031ddcd7066e, 8e607312f298252af2cc95695864d1578daddb36 and ad830968946baa0f354ff32e5522209b5959b1cd.

**Comment by johnny-mnemonic** [comment]
@lenticularis39 : For 8e60731 you'll also need the second part of https://github.com/johnny-mnemonic/linux-ia64/commit/d50e1168aaf45579c4b6d1871ad03d6581ebb931 to have an effect on `PAGE_SHIFT` for ia64. Also see https://github.com/torvalds/linux/commit/5394f1e9b687bcf26595cabf83483e568676128d for the upstream commit that introduced these new HAVE_PAGE_SIZE_* flags.

**Comment by lenticularis39** [comment]
@johnny-mnemonic We currently don't need to sync that, right? I'll add the second part as a separate commit into the 6.12-epic release.

**Comment by johnny-mnemonic** [comment]
Yeah, it's more like if you see https://github.com/linux-ia64/linux-ia64/commit/8e607312f298252af2cc95695864d1578daddb36 as implementing https://github.com/torvalds/linux/commit/5394f1e9b687bcf26595cabf83483e568676128d for ia64 then you'd also need the change in `arch/ia64/include/asm/page.h` to make it complete.
